--- Makefile	2013-09-03 16:07:48.248273987 +0400
+++ Makefile	2013-09-03 16:11:08.990579685 +0400
@@ -2,6 +2,7 @@
 builddir = /root/pinba_extension
 top_srcdir = /root/pinba_extension
 top_builddir = /root/pinba_extension
+PHP_VERSION = php5.3
 EGREP = /bin/grep -E
 SED = /bin/sed
 CONFIGURE_COMMAND = './configure'
@@ -17,12 +18,12 @@
 PHP_ZEND_EX =
 all_targets = $(PHP_MODULES) $(PHP_ZEND_EX)
 install_targets = install-modules install-headers
-prefix = /usr/lib64/php5.3
+prefix = /usr/lib64/${PHP_VERSION}
 exec_prefix = $(prefix)
 libdir = ${exec_prefix}/lib
-prefix = /usr/lib64/php5.3
+prefix = /usr/lib64/${PHP_VERSION}
 phplibdir = /root/pinba_extension/modules
-phpincludedir = /usr/lib64/php5.3/include/php
+phpincludedir = /usr/lib64/${PHP_VERSION}/include/php
 CC = cc
 CFLAGS = -g -O2
 CFLAGS_CLEAN = $(CFLAGS)
@@ -31,11 +32,11 @@
 CXX =
 CXXFLAGS =
 CXXFLAGS_CLEAN = $(CXXFLAGS)
-EXTENSION_DIR = /usr/lib64/php5.3/lib/extensions/no-debug-non-zts-20090626
-PHP_EXECUTABLE = /usr/lib64/php5.3/bin/php
+EXTENSION_DIR = ${DESTDIR}/usr/lib64/${PHP_VERSION}/lib/extensions/no-debug-non-zts-20090626
+PHP_EXECUTABLE = /usr/lib64/${PHP_VERSION}/bin/php
 EXTRA_LDFLAGS =
 EXTRA_LIBS =
-INCLUDES = -I/usr/lib64/php5.3/include/php -I/usr/lib64/php5.3/include/php/main -I/usr/lib64/php5.3/include/php/TSRM -I/usr/lib64/php5.3/include/php/Zend -I/usr/lib64/php5.3/include/php/ext -I/usr/lib64/php5.3/include/php/ext/date/lib
+INCLUDES = -I/usr/lib64/${PHP_VERSION}/include/php -I/usr/lib64/${PHP_VERSION}/include/php/main -I/usr/lib64/${PHP_VERSION}/include/php/TSRM -I/usr/lib64/${PHP_VERSION}/include/php/Zend -I/usr/lib64/${PHP_VERSION}/include/php/ext -I/usr/lib64/${PHP_VERSION}/include/php/ext/date/lib
 LFLAGS =
 LDFLAGS =
 SHARED_LIBTOOL =
