#!/sbin/runscript

start() {
	ebegin "Starting ArangoDB"
	start-stop-daemon \
		--start \
		--exec /usr/sbin/arangod \
		--pidfile /var/run/arangod.pid \
		--make-pidfile \
		--user arangodb \
		--background \
        --wait 5000 \
        --progress
	eend $? "Failed to start ArangoDB"
}

stop() {
	ebegin "Stopping ArangoDB"
	start-stop-daemon --stop --pidfile /var/run/arangod.pid --retry SIGTERM/5
	eend $? "Failed to stop ArangoDB"
}
