#!/sbin/runscript
# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

start() {
  start-stop-daemon --start --exec harbd --pidfile ${PIDFILE} --user ${USER}:${GROUP} --progress --background --make-pidfile -1 ${LOGFILE} -2 ${LOGFILE} --wait 2000 -- ${ARGS}
}

stop() {
  start-stop-daemon --stop --exec harbd --pidfile ${PIDFILE} --user ${USER}:${GROUP} --progress -1 ${LOGFILE} -2 ${LOGFILE} --retry SIGTERM/5 -- ${ARGS}
}

